In [1]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
# create a vector
v = np.array([ 1, 40, 2, -3])

# find and report the max and min values
minval = np.min(v)
maxval = np.max(v)

print("Min, max: %g,%g" %(minval, maxval))

# now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)

print("Min, max indices: %g,%g" %(minidx, maxidx)), print(" ")

Min, max: -3,40
Min, max indices: 3,1
 


(None, None)

In [4]:
# repeat with matrix
M = np.array([ [0, 1, 10],
              [20, 8, 5]
             ])
print(M), print(" ")

# various minima in this matrix
minvals1 = np.min(M) # min of entire matrix
minvals2 = np.min(M, axis = 0) # min of each column (across rows)
minvals3 = np.min(M, axis = 1) # min of each row (across columns)

print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


In [5]:
# various minima in this matrix
minidx1 = np.argmin(M) # min of entire matrix
minidx2 = np.argmin(M, axis = 0) # min of each column (across rows)
minidx3 = np.argmin(M, axis = 1) # min of each row (across columns)

print(minidx1)
print(minidx2)
print(minidx3)

0
[0 0 1]
[0 2]


In [6]:
## Using pytorch

# create a vector
v = torch.tensor([1, 40, 2, -3])

# find and report the max and min values
minval = torch.min(v)
maxval = torch.max(v)

print("Min, max: %g,%g" %(minval, maxval))

# now for argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print("Min, max indices: %g,%g" %(minidx, maxidx)), print(" ")

Min, max: -3,40
Min, max indices: 3,1
 


(None, None)

In [7]:
# repeat with matrix
M = torch.tensor([ [0, 1, 10],
                   [20, 8, 5]
                 ])
print(M), print(" ")

# various minima in this matrix
min1 = torch.min(M) # min of entire matrix
min2 = torch.min(M, axis = 0) # min of each column (across rows)
min3 = torch.min(M, axis = 1) # min of each row (across columns)

print(min1), print(" ")
print(min2), print(" ")
print(min2.values)
print(min2.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
tensor([0, 0, 1])
