In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
# define a dropout instance and make some data
prob = .5

dropout = nn.Dropout(p = prob)
x = torch.ones(10)

# let's see what dropout means
y = dropout(x)
print(x)
print(y*(1-prob))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 0., 0., 0., 0., 1., 0., 0., 1., 1.])
tensor(0.8000)


In [5]:
# dropout is turned off when evaluating the model
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [6]:
# annoyingly, F.dropout() is not deactivated in eval mode:
dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([2., 0., 0., 2., 0., 2., 2., 2., 2., 2.])
tensor(1.4000)


In [8]:
# but you can manually switch it off
y = F.dropout(x, training = False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [9]:
# the model needs to be reset after toggling into eval mode

dropout.train()
y = dropout(x)
print(y) # with dropout

dropout.eval()
y = dropout(x)
print(y) # without dropout

# dropout.train()
y = dropout(x)
print(y) # still w/o dropout

tensor([2., 0., 2., 0., 2., 2., 2., 0., 0., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
